import os
import sys
import sqlite3
from fastapi import APIRouter
from fastapi.responses import HTMLResponse, Response

router = APIRouter()

APP_ID = "pricecalc"

_DB_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "..", "apps", "pricecalc", "data.db")


def _hub():
    return sys.modules.get("backend.apphub")

_STRINGS = {
    "en": {
        "service":   "Service",
        "hours":     "Hours",
        "cost":      "Cost",
        "total_h":   "Total hours",
        "rate":      "Hourly rate",
        "subtotal":  "Subtotal",
        "discount":  "Discount",
        "total":     "Total",
        "deposit":   "Deposit",
        "remaining": "Remaining after deposit",
        "footer":      "Generated by mvmOS QuoteBuilder",
        "fixed_label": "fixed",
        "print":       "Print",
    },
    "bg": {
        "service":     "Услуга",
        "hours":       "Часове",
        "cost":        "Цена",
        "total_h":     "Общо часове",
        "rate":        "Цена на час",
        "subtotal":    "Сума",
        "discount":    "Отстъпка",
        "total":       "Общо",
        "deposit":     "Капаро",
        "remaining":   "Остатък след капарото",
        "footer":      "Генерирано от mvmOS QuoteBuilder",
        "fixed_label": "фикс.",
        "print":       "Печат",
    },
}


def _esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _get_db():
    if not os.path.exists(_DB_PATH):
        return None
    conn = sqlite3.connect(_DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def _private_page():
    return HTMLResponse("""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>QuoteBuilder</title>
<style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;
height:100vh;margin:0;background:#1e1e2e;color:#a6adc8;flex-direction:column;gap:12px}
.icon{font-size:3rem}.msg{font-size:1.1rem;font-weight:700;color:#cdd6f4}
.sub{font-size:.9rem;color:#6c7086}</style>
</head><body>
<div class="icon">🔒</div>
<div class="msg">QuoteBuilder is private</div>
<div class="sub">Access is not available to the public.</div>
</body></html>""", status_code=403)


@router.get("/{token}", response_class=HTMLResponse)
async def public_quote(token: str):
    hub = _hub()
    if hub and not hub.is_app_public(APP_ID):
        return _private_page()

    conn = _get_db()
    if not conn:
        return Response("Not found", status_code=404)

    proj = conn.execute("SELECT * FROM projects WHERE public_token=?", (token,)).fetchone()
    if not proj:
        conn.close()
        return Response("Not found", status_code=404)

    svcs = conn.execute(
        "SELECT * FROM project_services WHERE project_id=? ORDER BY id", (proj["id"],)
    ).fetchall()
    settings_rows = conn.execute(
        "SELECT key, value FROM settings WHERE public_user_id=?", (proj["public_user_id"],)
    ).fetchall()
    conn.close()

    gs = {"hourly_rate": 50, "currency": "€", "deposit_percent": 30}
    for r in settings_rows:
        if r["key"] in ("hourly_rate", "deposit_percent"):
            try:
                gs[r["key"]] = float(r["value"])
            except (TypeError, ValueError):
                pass
        else:
            gs[r["key"]] = r["value"]

    keys = proj.keys()
    rate         = proj["hourly_rate"]     if proj["hourly_rate"]     is not None else gs["hourly_rate"]
    deposit_pct  = proj["deposit_percent"] if proj["deposit_percent"] is not None else gs["deposit_percent"]
    discount_pct = proj["discount_percent"] or 0
    currency     = gs.get("currency", "€")
    show_hours   = bool(proj["show_hours"]) if "show_hours" in keys else True
    show_rate    = bool(proj["show_rate"])  if "show_rate"  in keys else True
    lang         = (proj["public_lang"] if "public_lang" in keys else None) or "en"
    if lang not in _STRINGS:
        lang = "en"

    s = _STRINGS[lang]

    def sv_fixed(sv):
        return sv["fixed_price"] if "fixed_price" in sv.keys() and sv["fixed_price"] is not None else None

    def sv_cost(sv):
        fp = sv_fixed(sv)
        return fp if fp is not None else sv["hours"] * rate

    def fmt_hm(hours):
        h = int(hours)
        m = round((hours - h) * 60 / 10) * 10
        if m >= 60:
            h += 1; m = 0
        return f"{h}h {m:02d}m" if m else f"{h}h"

    total_hours  = sum(sv["hours"] for sv in svcs if sv_fixed(sv) is None)
    subtotal     = sum(sv_cost(sv) for sv in svcs)
    discount_amt = subtotal * (discount_pct / 100)
    total        = subtotal - discount_amt
    deposit_amt  = total * (deposit_pct / 100)
    remainder    = total - deposit_amt

    def fmt(n):
        return f"{n:.2f} {currency}"

    # ── service rows ──────────────────────────────────────────────────────────

    svc_rows = ""
    for sv in svcs:
        fp        = sv_fixed(sv)
        cost      = fp if fp is not None else sv["hours"] * rate
        if show_hours:
            hrs_str  = f"— ({s['fixed_label']})" if fp is not None else fmt_hm(sv["hours"])
            hrs_cell = f'<td class="num">{hrs_str}</td>'
        else:
            hrs_cell = ""
        desc      = sv["description"] if "description" in sv.keys() and sv["description"] else ""
        desc_html = f'<div class="svc-desc">{_esc(desc)}</div>' if desc else ""
        svc_rows += f'<tr><td>{_esc(sv["name"])}{desc_html}</td>{hrs_cell}<td class="num amt">{_esc(fmt(cost))}</td></tr>'

    th_hours  = f'<th class="num">{_esc(s["hours"])}</th>' if show_hours else ""
    col_hours = '<col style="width:110px">' if show_hours else ""
    colgroup  = f'<colgroup><col>{col_hours}<col style="width:120px"></colgroup>'
    thead     = f'<tr><th>{_esc(s["service"])}</th>{th_hours}<th class="num">{_esc(s["cost"])}</th></tr>'

    # ── summary rows ──────────────────────────────────────────────────────────

    def srow(label, value, cls=""):
        cls_attr = f' class="{cls}"' if cls else ""
        return f'<tr{cls_attr}><td class="lbl">{_esc(label)}</td><td class="num val">{_esc(value)}</td></tr>'

    summary = ""
    if show_hours and total_hours > 0:
        summary += srow(s["total_h"], fmt_hm(total_hours))
    if show_rate and total_hours > 0:
        summary += srow(s["rate"], f"{rate:.2f} {currency}/h")
    summary += srow(s["subtotal"], fmt(subtotal))
    if discount_pct > 0:
        pct = f"{discount_pct:.4g}%"
        summary += srow(f'{s["discount"]} ({pct})', f"−{fmt(discount_amt)}", "discount")
    summary += srow(s["total"], fmt(total), "total")
    if deposit_pct > 0:
        pct = f"{deposit_pct:.4g}%"
        summary += srow(f'{s["deposit"]} ({pct})', fmt(deposit_amt), "deposit")
        summary += srow(s["remaining"], fmt(remainder))

    html = f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{_esc(proj["name"])} — QuoteBuilder</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    background: #f7f8fa;
    color: #1a1a2e;
    min-height: 100vh;
    padding: 32px 16px 60px;
  }}
  .card {{
    background: #fff;
    border: 1px solid #e2e4ea;
    border-radius: 10px;
    max-width: 640px;
    margin: 0 auto;
    overflow: hidden;
    box-shadow: 0 2px 12px rgba(0,0,0,.06);
  }}
  .card-header {{ padding: 22px 28px 18px; border-bottom: 1px solid #e2e4ea; }}
  .brand {{ font-size: .74rem; color: #aaa; margin-bottom: 5px; letter-spacing: .05em; text-transform: uppercase; }}
  h1 {{ font-size: 1.3rem; font-weight: 700; }}
  .card-body {{ padding: 24px 28px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  .svc-table th {{
    font-size: .68rem; text-transform: uppercase; letter-spacing: .06em; color: #999;
    text-align: left; padding: 0 0 8px; border-bottom: 2px solid #e2e4ea;
  }}
  .svc-table th.num {{ text-align: right; }}
  .svc-table td {{ padding: 9px 0; font-size: .88rem; border-bottom: 1px solid #f0f1f5; vertical-align: top; }}
  .svc-desc {{ font-size: .78rem; color: #888; margin-top: 3px; }}
  .svc-table tr:last-child td {{ border-bottom: none; }}
  .num {{ text-align: right; white-space: nowrap; }}
  .amt {{ font-weight: 500; }}
  .summary-wrap {{ margin-top: 20px; border-top: 2px solid #e2e4ea; padding-top: 14px; }}
  .summary-table td {{ padding: 5px 0; font-size: .88rem; }}
  .summary-table .lbl {{ color: #666; }}
  .summary-table .val {{ text-align: right; font-weight: 500; white-space: nowrap; padding-left: 24px; }}
  .summary-table tr.discount .lbl,
  .summary-table tr.discount .val {{ color: #dc2626; }}
  .summary-table tr.total td {{ font-size: 1rem; font-weight: 700; color: #2563eb; padding-top: 10px; border-top: 1px solid #e2e4ea; }}
  .summary-table tr.deposit .val {{ color: #16a34a; }}
  .footer {{ padding: 12px 28px; border-top: 1px solid #e2e4ea; font-size: .72rem; color: #bbb; text-align: right; }}
  .print-btn {{
    display: block;
    margin: 20px auto 0;
    max-width: 640px;
    text-align: right;
  }}
  .print-btn button {{
    background: #2563eb;
    color: #fff;
    border: none;
    border-radius: 6px;
    padding: 8px 20px;
    font-size: .85rem;
    cursor: pointer;
    font-family: inherit;
  }}
  .print-btn button:hover {{ background: #1d4ed8; }}
  @media (max-width: 480px) {{
    .card-header, .card-body, .footer {{ padding-left: 16px; padding-right: 16px; }}
  }}
  @media print {{
    body {{ background: #fff; padding: 0; }}
    .print-btn {{ display: none; }}
    .card {{ border: none; box-shadow: none; border-radius: 0; }}
  }}
</style>
</head>
<body>
<div class="card">
  <div class="card-header">
    <div class="brand">QuoteBuilder</div>
    <h1>{_esc(proj["name"])}</h1>
  </div>
  <div class="card-body">
    <table class="svc-table">
      {colgroup}
      <thead>{thead}</thead>
      <tbody>{svc_rows}</tbody>
    </table>
    <div class="summary-wrap">
      <table class="summary-table" style="width:100%">
        <col style="width:100%"><col>
        {summary}
      </table>
    </div>
  </div>
  <div class="footer">{_esc(s["footer"])}</div>
</div>
<div class="print-btn">
  <button onclick="window.print()">{_esc(s["print"])}</button>
</div>
</body>
</html>"""

    return HTMLResponse(html)
